export default {
	label: "Ai Interview",
	appname: `Interviews`,
	paths: [
		{
			title: "VP of Ai",
			path: "/Ai/VP",
			qa: [
				{ q: "Purpose of machine learning?", a: "Learn from data" },
				{ q: "NLP task example?", a: "Sentiment analysis" },
				{ q: "ML algorithm for classification?", a: "Decision tree" },
				{ q: "Image processing task?", a: "Object detection" },
				{ q: "Python AI library?", a: "TensorFlow" },
				{ q: "Programming language for AI?", a: "Python" },
				{
					q: "Text understanding in AI?",
					a: "Natural language processing",
				},
				{ q: "AI mimicking the brain?", a: "Neural networks" },
				{ q: "AI creating images?", a: "Generative AI" },
				{ q: "Data role in AI?", a: "Essential for learning" },
				{
					q: "Type of unlabeled learning?",
					a: "Unsupervised learning",
				},
				{ q: "Computer vision application?", a: "Self-driving cars" },
				{ q: "Reinforcement learning method?", a: "Trial and error" },
				{
					q: "Improve ML model performance?",
					a: "More data, better features",
				},
				{ q: "Basic ML algorithm?", a: "Linear regression" },
				{ q: "Handling messy data?", a: "Data cleaning" },
				{ q: "Common NLP task?", a: "Text summarization" },
				{ q: "AI for games?", a: "Reinforcement learning" },
				{ q: "Python data manipulation library?", a: "Pandas" },
				{ q: "AI analyzing emotions?", a: "Sentiment analysis" },
				{
					q: "Type of neural network?",
					a: "Convolutional Neural Network (CNN)",
				},
				{ q: "Detecting faces in images?", a: "Computer vision" },
				{ q: "Key AI skill?", a: "Problem solving" },
				{
					q: "Explain overfitting?",
					a: "Model memorizes training data",
				},
				{ q: "AI branch for robots?", a: "Robotics" },
				{
					q: "Translating between languages?",
					a: "Machine translation",
				},
				{ q: "Finding patterns in data?", a: "Unsupervised learning" },
				{ q: "Statistical ML tool?", a: "R programming language" },
				{ q: "AI-powered image editing?", a: "Generative AI" },
				{ q: "AI writing code?", a: "Code generation" },
				{ q: "Finding image similarities?", a: "Computer vision" },
				{
					q: "Extracting text from images?",
					a: "Optical Character Recognition (OCR)",
				},
				{ q: "AI in finance?", a: "Fraud detection" },
				{ q: "Dataset for training?", a: "Labeled data" },
				{ q: "Measuring ML model success?", a: "Performance metrics" },
				{ q: "Challenges for AI?", a: "Bias, explainability" },
				{ q: "AI creating music?", a: "Generative AI" },
				{ q: "AI playing chess?", a: "Reinforcement learning" },
				{ q: "Data representation in ML?", a: "Features" },
				{ q: "Prepping images for AI?", a: "Image preprocessing" },
				{ q: "Task for NLP?", a: "Machine translation" },
				{ q: "ML for time series?", a: "Forecasting" },
				{ q: "Understanding AI decisions?", a: "Explainable AI (XAI)" },
				{
					q: "Type of deep learning?",
					a: "Recurrent Neural Network (RNN)",
				},
				{ q: "Data understanding tool?", a: "Data visualization" },
				{
					q: "Virtual assistant tech?",
					a: "Natural language processing",
				},
				{ q: "Handling large datasets?", a: "Big data tools" },
				{ q: "AI hardware acceleration?", a: "GPUs" },
				{ q: "AI analyzing video?", a: "Computer vision" },
				{
					q: "Improving chatbot responses?",
					a: "More data, better NLP",
				},
				{ q: "Making ethical AI?", a: "Fairness, transparency" },
				{ q: "Finding spam emails?", a: "Text classification" },
				{
					q: "Popular supervised algorithm?",
					a: "Support Vector Machine (SVM)",
				},
				{ q: "Pre-trained AI models?", a: "Transfer learning" },
				{ q: "Building AI product?", a: "Software development" },
				{ q: "Type of unsupervised learning?", a: "Clustering" },
				{ q: "Image classification tool?", a: "CNN" },
				{ q: "AI in healthcare?", a: "Diagnosis assistance" },
				{
					q: "Customer preference prediction?",
					a: "Recommender systems",
				},
				{ q: "Improving AI speed?", a: "Hardware optimization" },
				{ q: "Type of reinforcement learning?", a: "Q-learning" },
				{ q: "Data in rows and columns?", a: "Tabular data" },
				{ q: "Deep learning framework?", a: "PyTorch" },
				{ q: "Understanding human speech?", a: "Speech recognition" },
				{ q: "Finding best ML model?", a: "Hyperparameter tuning" },
				{
					q: "Making AI more powerful?",
					a: "More data, bigger models",
				},
				{ q: "Common deep learning task?", a: "Image classification" },
				{ q: "Text classification tool?", a: "Naive Bayes" },
				{ q: "Analyzing customer reviews?", a: "Sentiment analysis" },
				{ q: "Identifying objects in images?", a: "Object detection" },
				{ q: "AI's impact on society?", a: "Significant potential" },
				{ q: "Making AI learn faster?", a: "Better algorithms" },
				{
					q: "AI creating different text styles?",
					a: "Text generation",
				},
				{ q: "AI replacing human jobs?", a: "Potential risk" },
				{
					q: "AI making investment decisions?",
					a: "Algorithmic trading",
				},
				{ q: "Understanding medical images?", a: "Computer vision" },
				{ q: "Identifying fake news?", a: "NLP techniques" },
				{ q: "AI designing websites?", a: "Emerging application" },
				{
					q: "Detecting network anomalies?",
					a: "ML for cybersecurity",
				},
				{
					q: "Optimizing manufacturing processes?",
					a: "Industrial AI",
				},
				{ q: "Predicting customer churn?", a: "Supervised learning" },
				{ q: "Grouping similar products?", a: "Clustering" },
				{
					q: "Extracting data from forms?",
					a: "Computer vision + NLP",
				},
			],
		},
	],
}
